---
- name: Install package Certbot
  when: certbot_install_method == 'package'
  block:
    - name: Install Certbot.
      ansible.builtin.package:
        name: "{{ certbot_package }}"
        state: present
    - name: Set Certbot script variable.
      ansible.builtin.set_fact:
        certbot_script: "{{ certbot_package }}"

- name: Install snap Certbot
  when: certbot_install_method == 'snap'
  block:
    - name: Ensure snapd is installed.
      ansible.builtin.package:
        name: snapd
        state: present
      register: snapd_install
    - name: Ensure snapd is enabled.
      ansible.builtin.systemd:
        name: snapd.socket
        enabled: true
        state: started
    - name: Enable classic snap support.
      ansible.builtin.file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
      when: ansible_os_family != "Debian"
    - name: Update snap after install.
      ansible.builtin.shell: snap install core; snap refresh core
      changed_when: true
      failed_when: false
      when: snapd_install.changed # noqa: no-handler
    - name: Install certbot via snap.
      community.general.snap:
        name: certbot
        classic: true
    - name: Symlink certbot into place.
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link
      ignore_errors: "{{ ansible_check_mode }}"
    - name: Set Certbot script variable.
      ansible.builtin.set_fact:
        certbot_script: /usr/bin/certbot

- name: Install source Certbot
  when: certbot_install_method == 'source'
  block:
    - name: Clone Certbot into configured directory.
      ansible.builtin.git:
        repo: "{{ certbot_repo }}"
        dest: "{{ certbot_dir }}"
        version: "{{ certbot_version }}"
        update: "{{ certbot_keep_updated }}"
        force: true
    - name: Set Certbot script variable.
      ansible.builtin.set_fact:
        certbot_script: "{{ certbot_dir }}/certbot-auto"
    - name: Ensure certbot-auto is executable.
      ansible.builtin.file:
        path: "{{ certbot_script }}"
        mode: '0755'
