---
- name: Ensure configuration directories
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/ensure-directories.yml"

- name: Install certbot.
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/install/install-certbot.yml"

- name: Setup certbot DNS plugin
  when:
    - certbot_dns_plugin is defined
  block:
    - name: Install certbot DNS plugin
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install/install-dns-plugin.yml"
    - name: Config certbot for DNS
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/config/config-certbot-dns.yml"

- name: Certbot create certificate
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/create-cert.yml"
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing | bool
  loop_control:
    loop_var: cert_item

- name: Delete Certificates.
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/delete-cert.yml"
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_delete_certs | bool
  loop_control:
    loop_var: cert_item

- name: Setup/Remove cron job for certbot renewal (if configured).
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/modify/setup-cron.yml"
