---
certbot_package: certbot

certbot_supported_dns_plugins:
 - rfc2136
 - cloudflare
 - digitalocean
 - luadns
 - route53

__set_dns_default: --dns-{{ certbot_dns_plugin }}-credentials {{ certbot_letsencrypt_credentials_dir }}/{{ certbot_dns_plugin }}.ini
__set_dns_rfc2136: "{{ __set_dns_default }} --dns-rfc2136-propagation-seconds 120"
__set_dns_digitalocean: "{{ __set_dns_default }} --dns-digitalocean-propagation-seconds 60"
__set_dns_luadns: "{{ __set_dns_default }} --dns-luadns-propagation-seconds 60"
__set_dns_route53: "--dns-route53-propagation-seconds 60"
__set_dns_cloudflare: "{{ __set_dns_default }} --dns-cloudflare-propagation-seconds 30"
__set_create_cert_with_credential: "{{ lookup('ansible.builtin.vars', '__set_dns_' + certbot_dns_plugin) }}"

certbot_create_command: >-
  {{ certbot_script }} certonly
  {{ '--hsts' if certbot_hsts else '' }}
  {{ '--test-cert' if certbot_testmode else '' }}
  --noninteractive
  --agree-tos
  --dns-{{ certbot_dns_plugin }}
  {{ __set_create_cert_with_credential }}
  --email {{ cert_item.email | default(certbot_admin_email) }}
  -d {{ cert_item.domains | join(',') }}
  {{ '--deploy-hook /etc/letsencrypt/renewal-hooks/deploy/reload_services.sh' if certbot_create_reload_services else '' }}

certbot_delete_command: >-
  {{ certbot_script }} delete --noninteractive
  --cert-name {{ cert_item.domains | first | replace('*.', '') }}
